---
# tasks file for kube-master
  - name: Configure Docker Repository 
    yum_repository:
      description: DOCKER YUM repo
      name: docker
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: no
      state: present
  - name: Install Docker
    package:
      name: docker-ce-18.09.1-3.el7.x86_64
      skip_broken: yes
      state: present
  - service:
      name: docker
      state: started
      enabled: yes

  - name: Configuring Kubernetes Repository...
    yum_repository:
      name: kubernetes
      description: Kubernetes YUM Repository 
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch 
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      state: present
  - name: Permissive SeLinux
    selinux:
      policy: targeted
      state: permissive
    when: false
 
  - name: Installing Kubelet, Kubeadm and, Kubect1...
    package:
      name:
        - iproute-tc
        - kubelet
        - kubeadm
        - kubectl

  - name: Staring kubelet Service...
    service:
      name: kubelet
      state: started
      enabled: yes

  - name: Checking Cgroup Driver...
    shell: docker info | grep -i cgroup

  - name: Making systemd as Cgroup Driver...
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
    notify: RestartDocker

  - name: setting the system variables...
    copy: 
      src: k8s.conf
      dest: /etc/sysctl.d/k8s.conf
  - name: Refresh System variables
    shell: sysctl --system

  - name: Initializing Cluster...
    command: kubeadm init --pod-network-cidr=10.240.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem

  - name: Generating Join Command and Token...
    command: kubeadm token create  --print-join-command
    register: kubeadm_join

  - name:  Join Kubernetes Node in Cluster with this command...  
    debug: 
      var: kubeadm_join.stdout

  - name: Saving join Command...
    copy: 
      content: "{{ kubeadm_join.stdout }}"
      dest: joincmd.sh
      mode: a+x
    delegate_to: localhost

  - name: Creating $HOME/.kube/ directory...
    file:
      path: $HOME/.kube
      state: directory
  - name: Command to get the public IP address
    command: curl ifconfig.me 
    register: public_ip
 
  - name: Copying config file to .kube directory 
    copy: 
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      force: yes
      remote_src: yes
  
      #  - name: Change kubeconfig file permission
      #file:
      #path: $HOME/.kube/config 
      #owner: "{{ ansible_effective_user_id }}"
      #group: "{{ ansible_effective_group_id }}"
  - name: changing owner permission
    shell: "chown $(id -u):$(id -g) $HOME/.kube/config"

  - name: Setting up Flannel...
    command:  kubectl apply  -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    ignore_errors: yes

   
