---
# tasks file for kube-node
  - name: Configure Docker Repository
    yum_repository:
      description: DOCKER YUM repo
      name: docker
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      gpgcheck: no
      state: present
  - name: Install Docker
    package:
      name: docker-ce-18.09.1-3.el7.x86_64
      skip_broken: yes
      state: present
  - service:
      name: docker
      state: started
      enabled: yes
  - name: Configuring Kubernetes Repository...
    yum_repository:
      name: Kubernetes
      description: Kubernetes YUM Repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      state: present
  - name: Permissive SeLinux
    selinux:
      policy: targeted
      state: permissive
    when: false

  - name: Installing Kubelet, Kubeadm and, Kubect1...
    package:
      name:
        - iproute-tc
        - kubelet
        - kubeadm
        - kubectl
  
  - name: Staring kubelet Service...
    service:
      name: kubelet
      state: started
      enabled: yes

  - name: Checking Cgroup Driver...
    shell: docker info | grep -i cgroup
  
  - name: Making systemd as Cgroup Driver...
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
    register: RestartDocker
  
  - name: Restaring Docker...
    service: 
      name: docker
      state: restarted
    when: RestartDocker.changed
  
  - name: update sysctl param 
    copy: 
      src: k8s.conf
      dest: /etc/sysctl.d/k8s.conf
      owner: root
      group: root
    register: result
  
  - name: System reload...
    shell: sysctl --system 
    when: result.changed

  - name: Coping Join command...
    copy: 
      src: joincmd.sh 
      dest: /root
      mode: a+x

  - name: This is join command...
    command: cat /root/joincmd.sh

  - name: Joining the Node... 
    shell: bash /root/joincmd.sh

  - name: Download prometheus exporter
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz
      dest: .
  - name: make /prometheus directory
    file:
      path: /prometheus
      state: directory

  - name: Unarchive Prometheus exporter
    unarchive:
      src: prometheus-2.27.0.linux-amd64.tar.gz
      dest: /prometheus

   
    

