- hosts: localhost
  tasks: 
  - name: Configuring AWS Dynamic Inventory
    copy: 
      src: "{{ item }}"
      dest: /etc/ansible
    with_items: 
      - inventory/ec2.py
      - inventory/ec2.ini
      - inventory/ansible.cfg
      - inventory/README.md
      - ./../infra/devops_keypair.pem

  - name: Make Dynamic Inventory files Executable 
    file: 
      dest: "{{ item }}"
      mode: a+x
    with_items: 
      - /etc/ansible/ec2.py
      - /etc/ansible/ec2.ini
   
  - name: changing file permission
    file:
      dest: "{{ item }}"
      mode: 0400 
      owner: ec2-user
    with_items:
      - /etc/ansible/devops_keypair.pem
  - name: changing file permission
    file:
      dest: "{{ item }}"
      mode: 0600
    with_items:
      - $HOME/.ssh/authorized_keys



  - name: copy the keypair to the ansible configiration directory 
    copy: 
      src: ./../infra/devops_keypair.pem
      dest: /etc/ansible/devops_keypair.pem

 
   
